version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ${PWD}/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro 
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports: 
      - 3100:3000