version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ${PWD}/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${PWD}/prometheus/data:/promtheus
    depends_on:
      - cadvisor
      - node-exporter
  node-exporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      #- --collector.cpu.info
      #- --collector.perf.cpus=""
     # - --collector.powersupply.ignored-supplies="^$"
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs="/" 
      #- --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)
    ports:
      - "9100:9100"
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports: 
      - 3000:3000
