version: '3.2'
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      #- --collector.cpu.info
      #- --collector.perf.cpus=""
     # - --collector.powersupply.ignored-supplies="^$"
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs="/" 
      #- --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)
    ports:
      - "9100:9100"
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

